###
GET http://localhost:8080/sample/selectBoardList
Content-Type: application/json

###
GET http://localhost:8080/sample/getBoardList
Content-Type: application/json


###
GET http://localhost:8080/board
Content-Type: application/json
